### ISSUE TITLE
Expirable Setting

### ISSUE THREAD

**Issue by putyourlightson** [studioespresso/craft3-craftnet-cp#1]
Thanks for the great plugin!! It would be great to have an `expirable` setting as often we'll want to set this to false when gifting a license.

**Comment by janhenckens** [comment]
Hey Ben

Hadn't added that since `expirable` default to `false` ([docs](https://docs.api.craftcms.com/plugin-licenses.html#create-a-plugin-license)). I'll add it as a light-switch to the interface for it!

**Comment by putyourlightson** [comment]
Ah ok, would still make a nice addition though if you find the time, thanks!!

**Comment by janhenckens** [comment]
Found a small bug and had to do some minor improvements so added this along the way.
Thanks for the suggestion!

**Comment by putyourlightson** [comment]
Excellent, thank you!
