### ISSUE TITLE
Feature Request: Add sales charts

### ISSUE THREAD

**Issue by putyourlightson** [studioespresso/craft3-craftnet-cp#3]
Hi Jan, any chance you'd consider adding sales charts to the plugin? Andrew Welch of @nystudio107 and I were chatting last night that we were both thinking of doing this but since you already have this great plugin, it would make much more sense to add here :)

**Comment by janhenckens** [comment]
Sure, that sounds neat! Not entirely my speciality so if you have method or library in mind, feel free to share or make a pr :)

**Comment by putyourlightson** [comment]
https://apexcharts.com is excellent.

**Comment by putyourlightson** [comment]
FYI seems likely that either @nystudio107 or I will build this out ourselves.
